=== rhythm-games-tampere/itgmania/Docs/Luadoc/Lua.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.stepmania.com"
 xmlns="http://www.stepmania.com"
 elementFormDefault="qualified">

<xs:element name="Lua">
	<xs:complexType>
		<xs:all>
			<xs:element name="Singletons" type="Singletons" />
			<xs:element name="Classes" type="Classes" />
			<xs:element name="Namespaces" type="Namespaces" />
			<xs:element name="GlobalFunctions" type="GlobalFunctions" />
			<xs:element name="Enums" type="Enums" />
			<xs:element name="Constants" type="Constants" />
			<xs:element name="Date" type="xs:date" />
			<xs:element name="Version" type="xs:string" />
		</xs:all>
	</xs:complexType>
</xs:element>


<xs:element name="Documentation">
	<xs:complexType>
		<xs:all>
			<xs:element name="Classes" type="Classes" />
			<xs:element name="Namespaces" type="Namespaces" />
			<xs:element name="GlobalFunctions" type="GlobalFunctions" />
			<xs:element name="Enums" type="Enums" />
		</xs:all>
	</xs:complexType>
</xs:element>

<xs:simpleType name="Identifier">
	<xs:restriction base="xs:string">
	<!-- Not totally valid since the following are not valid
	     identifiers in Lua.
		and	break	do	else		elseif
		end	false	for	function	if
		in	local	nil	not		or
		repeat	return	then	true		until
		while
	-->
		<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="IdentifierOrTable">
	<xs:restriction base="xs:string">
		<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*|\{[a-zA-Z_][a-zA-Z0-9_]*\}" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="IdentifierOrNonemptyString">
	<xs:restriction base="xs:string">
	<!-- XXX: Doesn't support double quoted strings. -->
		<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*|'[^']+'" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="IdentifierStringOrNumber">
	<xs:restriction base="xs:string">
		<xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*|'[^']+'|[0-9]+" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="ArgumentList">
	<xs:restriction base="xs:string">
		<xs:whiteSpace value="collapse" />
		<!-- ((IdentifierOrTable Identifier(, IdentifierOrTable Identifier)*(, ...)?)|...)? -->
		<xs:pattern value="((([a-zA-Z_][a-zA-Z0-9_]*|\{[a-zA-Z_][a-zA-Z0-9_]*\}) [a-zA-Z_][a-zA-Z0-9_]*( ?, ?([a-zA-Z_][a-zA-Z0-9_]*|\{[a-zA-Z_][a-zA-Z0-9_]*\}) [a-zA-Z_][a-zA-Z0-9_]*)*)( ?, ?\.\.\.)?|\.\.\.)?" />
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="Singletons">
	<xs:sequence>
		<xs:element name="Singleton" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:attribute name="name" type="Identifier" use="required" />
				<xs:attribute name="class" type="Identifier" use="required" />
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:group name="DocumentationGroup">
	<xs:sequence>
		<xs:choice>
			<xs:element name="Link" type="Link" />
			<!-- HTML elements we want to let through. -->
			<xs:element name="code" />
			<xs:element name="pre" />
			<xs:element name="br" />
			<xs:element name="del" />
		</xs:choice>
	</xs:sequence>
</xs:group>

<xs:complexType name="Description" mixed="true">
	<xs:group ref="DocumentationGroup" minOccurs="0" maxOccurs="unbounded"/>
</xs:complexType>

<xs:complexType name="Classes">
	<xs:sequence>
		<xs:element name="Class" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Description" type="Description"
					 minOccurs="0" maxOccurs="1" />
					<xs:element name="Function" type="Function"
					 minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="name" type="Identifier" use="required" />
				<xs:attribute name="base" type="Identifier" use="optional" />
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="Namespaces">
	<xs:sequence>
		<xs:element name="Namespace" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Description" type="Description"
					 minOccurs="0" maxOccurs="1" />
					<xs:element name="Function" type="Function"
					 minOccurs="0" maxOccurs="unbounded" />
			 	</xs:sequence>
				<xs:attribute name="name" type="Identifier" use="required" />
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="GlobalFunctions">
	<xs:sequence>
		<xs:element name="Function" type="Function"
		 minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="Function" mixed="true">
	<xs:group ref="DocumentationGroup" minOccurs="0" maxOccurs="unbounded" />
	<xs:attribute name="name" type="Identifier" use="required" />
	<xs:attribute name="theme" type="Identifier" use="optional" />
	<xs:attribute name="return" type="IdentifierOrTable" use="optional" />
	<xs:attribute name="arguments" type="ArgumentList" use="optional" />
	<xs:attribute name="since" type="xs:string" use="optional" />
</xs:complexType>

<xs:complexType name="Link" mixed="true">
	<xs:group ref="DocumentationGroup" minOccurs="0" maxOccurs="unbounded"/>
	<xs:attribute name="function" type="Identifier" use="optional" />
	<xs:attribute name="class" type="Identifier" use="optional" />
</xs:complexType>

<xs:complexType name="Enums">
	<xs:sequence>
		<xs:element name="Enum" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Description" type="Description"
					 minOccurs="0" maxOccurs="1" />
					<xs:element name="EnumValue" type="Constant"
					 minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="name" type="Identifier" use="required" />
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="Constants">
	<xs:sequence>
		<xs:element name="Constant" type="Constant"
		 minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>


<xs:complexType name="Constant">
	<xs:attribute name="name" type="IdentifierOrNonemptyString" use="required" />
	<xs:attribute name="value" type="IdentifierStringOrNumber" use="required" />
</xs:complexType>
</xs:schema>
<!-- vim: set tw=0: -->

=== rhythm-games-tampere/itgmania/Docs/Luadoc/Lua.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="Lua.xsl"?>

<Lua xmlns='http://www.stepmania.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://www.stepmania.com Lua.xsd'>
	<GlobalFunctions>
		<Function name='AllowOptionsMenu'/>
		<Function name='Alpha'/>
		<Function name='ArbitrarySpeedMods'/>
		<Function name='AreStagePlayerModsForced'/>
		<Function name='AreStageSongModsForced'/>
		<Function name='ArgsIfPlayerJoinedOrNil'/>
		<Function name='BGFitChoiceExample'/>
		<Function name='BGFitInputActor'/>
		<Function name='Basename'/>
		<Function name='BinaryToHex'/>
		<Function name='BoostColor'/>
		<Function name='Brightness'/>
		<Function name='Center1Player'/>
		<Function name='CloseConnection'/>
		<Function name='ColorDarkTone'/>
		<Function name='ColorLightTone'/>
		<Function name='ColorMidTone'/>
		<Function name='ColorToHSV'/>
		<Function name='ColorToHex'/>
		<Function name='ComboContinue'/>
		<Function name='ComboMaintain'/>
		<Function name='ComboPerRow'/>
		<Function name='ComboTransformCommand'/>
		<Function name='ComboUnderField'/>
		<Function name='ConfAspectRatio'/>
		<Function name='ConfDisplayMode'/>
		<Function name='ConfDisplayResolution'/>
		<Function name='ConfFullscreenType'/>
		<Function name='ConfRefreshRate'/>
		<Function name='ConnectToServer'/>
		<Function name='CourseDifficultyToLocalizedString'/>
		<Function name='CourseTypeToLocalizedString'/>
		<Function name='CustomDifficultyToColor'/>
		<Function name='CustomDifficultyToDarkColor'/>
		<Function name='CustomDifficultyToLightColor'/>
		<Function name='CustomDifficultyToLocalizedString'/>
		<Function name='DayOfMonth'/>
		<Function name='DayOfYear'/>
		<Function name='DeepCopy'/>
		<Function name='EvalUsesCheckpointsWithJudgments'/>
		<Function name='FailCombo'/>
		<Function name='FindSelection'/>
		<Function name='FindValue'/>
		<Function name='FormatNumSongsPlayed'/>
		<Function name='FormatNumberAndSuffix'/>
		<Function name='FormatPercentScore'/>
		<Function name='GameCompatibleModes'/>
		<Function name='GameOverOrContinue'/>
		<Function name='GameplayMargins'/>
		<Function name='GetCodeForGame'/>
		<Function name='GetCoursesToShowRanking'/>
		<Function name='GetCustomDifficulty'/>
		<Function name='GetDefaultOptionLines'/>
		<Function name='GetDisplayRatesForResolution'/>
		<Function name='GetEditModeSubScreens'/>
		<Function name='GetExtraColorThreshold'/>
		<Function name='GetGamePref'/>
		<Function name='GetGamePrefB'/>
		<Function name='GetGamePrefC'/>
		<Function name='GetGamePrefN'/>
		<Function name='GetGradeFromPercent'/>
		<Function name='GetLifeDifficulty'/>
		<Function name='GetOptionsListMapping'/>
		<Function name='GetPlayerOrMachineProfile'/>
		<Function name='GetProTiming'/>
		<Function name='GetRandomSongBackground'/>
		<Function name='GetReal'/>
		<Function name='GetRealInverse'/>
		<Function name='GetScreenAspectRatio'/>
		<Function name='GetServerName'/>
		<Function name='GetSongBackground'/>
		<Function name='GetSpeedModeAndValueFromPoptions'/>
		<Function name='GetTapPosition'/>
		<Function name='GetThemeAspectRatio'/>
		<Function name='GetThemePref'/>
		<Function name='GetTimeSinceStart'/>
		<Function name='GetTimingDifficulty'/>
		<Function name='GetTitleSafeH'/>
		<Function name='GetTitleSafeV'/>
		<Function name='GetUnlockEntryIndexToCelebrate'/>
		<Function name='GetUserPref'/>
		<Function name='GetUserPrefB'/>
		<Function name='GetUserPrefC'/>
		<Function name='GetUserPrefN'/>
		<Function name='HSV'/>
		<Function name='HSVA'/>
		<Function name='HSVToColor'/>
		<Function name='HSVToHex'/>
		<Function name='HasAlpha'/>
		<Function name='HideLightSetting' />
		<Function name='HitCombo'/>
		<Function name='HoldTiming'/>
		<Function name='Hour'/>
		<Function name='Hue'/>
		<Function name='InitGamePrefs'/>
		<Function name='InitUserPrefs'/>
		<Function name='IsArcade'/>
		<Function name='IsCourse'/>
		<Function name='IsFreePlay'/>
		<Function name='IsGame'/>
		<Function name='IsHome'/>
		<Function name='IsNetConnected'/>
		<Function name='IsNetSMOnline'/>
		<Function name='IsRoutine'/>
		<Function name='IsSMOnlineLoggedIn'/>
		<Function name='IsUsingWideScreen'/>
		<Function name='JsonDecode'/>
		<Function name='JsonEncode'/>
		<Function name='JudgmentLineToColor'/>
		<Function name='JudgmentLineToLocalizedString'/>
		<Function name='JudgmentLineToStrokeColor'/>
		<Function name='JudgmentTransformCommand'/>
		<Function name='JudgmentTransformSharedCommand'/>
		<Function name='LoadActor'/>
		<Function name='LoadActorFunc'/>
		<Function name='LoadActorWithParams'/>
		<Function name='LoadFallbackB'/>
		<Function name='LoadFont'/>
		<Function name='LoadProfileCustom'/>
		<Function name='LoadSongBackground'/>
		<Function name='LocalizeOptionItem'/>
		<Function name='Minute'/>
		<Function name='MissCombo'/>
		<Function name='MonthOfYear'/>
		<Function name='MonthToLocalizedString'/>
		<Function name='MonthToString'/>
		<Function name='MultiPlayerToLocalizedString'/>
		<Function name='MultiPlayerToString'/>
		<Function name='OldStyleStringToDifficulty'/>
		<Function name='OptionRowProTiming'/>
		<Function name='OptionRowScreenFilter'/>
		<Function name='OptionsNavigationMode'/>
		<Function name='OptionsRandomJukebox'/>
		<Function name='OptionsRowTest'/>
		<Function name='OptionsWeight'/>
		<Function name='PeakComboAwardToLocalizedString'/>
		<Function name='PlayModeToLocalizedString'/>
		<Function name='PlayerColor'/>
		<Function name='PlayerDarkColor'/>
		<Function name='PlayerNumberToLocalizedString'/>
		<Function name='PlayerNumberToString'/>
		<Function name='PlayerScoreColor'/>
		<Function name='PositionPerPlayer'/>
		<Function name='PrettyPercent'/>
		<Function name='PrintTable'/>
		<Function name='ProductFamily'/>
		<Function name='ProductID'/>
		<Function name='ProductVersion'/>
		<Function name='RadarCategoryToLocalizedString'/>
		<Function name='ReadGamePrefFromFile'/>
		<Function name='ReadPrefFromFile'/>
		<Function name='ReportStyle'/>
		<Function name='ResolveRelativePath'/>
		<Function name='RoutineSkinP1'/>
		<Function name='RoutineSkinP2'/>
		<Function name='Saturation'/>
		<Function name='SaveProfileCustom'/>
		<Function name='SaveScreenshot'/>
		<Function name='ScoreKeeperClass'/>
		<Function name='ScreenColor'/>
		<Function name='ScreenMetric'/>
		<Function name='ScreenSelectStyleChoices'/>
		<Function name='ScreenSelectStylePositions'/>
		<Function name='ScreenString'/>
		<Function name='Second'/>
		<Function name='SecondsToHHMMSS'/>
		<Function name='SecondsToMMSS'/>
		<Function name='SecondsToMMSSMsMs'/>
		<Function name='SecondsToMMSSMsMsMs'/>
		<Function name='SecondsToMSS'/>
		<Function name='SecondsToMSSMsMs'/>
		<Function name='SelectMusicOrCourse'/>
		<Function name='SelectProfileKeys'/>
		<Function name='Serialize'/>
		<Function name='SetGamePref'/>
		<Function name='SetThemePref'/>
		<Function name='SetUserPref'/>
		<Function name='ShowHoldJudgments'/>
		<Function name='ShowStandardDecoration'/>
		<Function name='SortOrderToLocalizedString'/>
		<Function name='SpeedModIncLarge'/>
		<Function name='SpeedModIncSize'/>
		<Function name='SpeedMods'/>
		<Function name='StageAwardToLocalizedString'/>
		<Function name='StageToColor'/>
		<Function name='StageToLocalizedString'/>
		<Function name='StageToStrokeColor'/>
		<Function name='StandardDecorationFromFile'/>
		<Function name='StandardDecorationFromFileOptional'/>
		<Function name='StandardDecorationFromTable'/>
		<Function name='StepsOrTrailToColor'/>
		<Function name='StepsOrTrailToCustomDifficulty'/>
		<Function name='StepsToCustomDifficulty'/>
		<Function name='StringToBlend'/>
		<Function name='TableStringLookup'/>
		<Function name='TapNoteScoreToLocalizedString'/>
		<Function name='TextBannerAfterSet'/>
		<Function name='ThemePrefRow'/>
		<Function name='ToEnumShortString'/>
		<Function name='Trace'/>
		<Function name='TrailToCustomDifficulty'/>
		<Function name='TwoPartSelection'/>
		<Function name='URLEncode'/>
		<Function name='UnlockRewardTypeToLocalizedString'/>
		<Function name='Var'/>
		<Function name='VersionDate'/>
		<Function name='VersionTime'/>
		<Function name='Warn'/>
		<Function name='Weekday'/>
		<Function name='WideScale'/>
		<Function name='WrapInActorFrame'/>
		<Function name='WriteGamePrefToFile'/>
		<Function name='WritePrefToFile'/>
		<Function name='Year'/>
		<Function name='alias_one'/>
		<Function name='alias_set'/>
		<Function name='approach'/>
		<Function name='assert'/>
		<Function name='check_stop_course_early'/>
		<Function name='clamp'/>
		<Function name='class'/>
		<Function name='collectgarbage'/>
		<Function name='color'/>
		<Function name='commify'/>
		<Function name='convert_text_to_indented_lines'/>
		<Function name='convert_xml_bgs'/>
		<Function name='create_bezier'/>
		<Function name='create_spline'/>
		<Function name='dofile'/>
		<Function name='error'/>
		<Function name='fapproach'/>
		<Function name='find_missing_strings_in_theme_translations'/>
		<Function name='force_to_range'/>
		<Function name='foreach_by_sorted_keys'/>
		<Function name='foreach_ordered'/>
		<Function name='gcinfo'/>
		<Function name='get_music_file_length'/>
		<Function name='get_sound_driver_list'/>
		<Function name='getenv'/>
		<Function name='getfenv'/>
		<Function name='getmetatable'/>
		<Function name='ipairs'/>
		<Function name='ivalues'/>
		<Function name='join'/>
		<Function name='lerp'/>
		<Function name='lerp_color'/>
		<Function name='load'/>
		<Function name='loadfile'/>
		<Function name='loadstring'/>
		<Function name='make_camel_aliases'/>
		<Function name='mbstrlen'/>
		<Function name='multiapproach'/>
		<Function name='new_numpad_entry'/>
		<Function name='newproxy'/>
		<Function name='next'/>
		<Function name='oitg_zoom_mode_actor'/>
		<Function name='pairs'/>
		<Function name='pause_controller_actor'/>
		<Function name='pcall'/>
		<Function name='pname'/>
		<Function name='print'/>
		<Function name='rawequal'/>
